### PR TITLE
Adopt Go modules, drop Glide.

### LINKED ISSUE #1: Adopt Go modules, drop Glide.
I'll submit a PR for this.

### PR DESCRIPTION
**Pull request by ghost**
Fixes #1 

Also, this PR:

* Better handles protobuf in Makefile.
* Deprecates `make vendor` and introduces `make revendor` (as inspired by the dex repo)
* Updates all go dependencies and fixes related regressions (e.g. here is a similar issue to one fixed in this PR: https://github.com/go-kit/kit/issues/597)
* Avoids Sirupsen vs. sirupsen case issues. 🤕 
* Introduces `vendor.go` pattern which allows for go module vendoring of packages `go install`'ed by Makefile. (as inspired by the dex repo)

current state: 

```
 vagrant@vagrant  goapi  goapi server
No configuration file loaded - using defaults
grpc on port: 10080
2020/01/08 03:16:29 http: TLS handshake error from [::1]:47604: remote error: tls: bad certificate
2020/01/08 03:16:29 http: TLS handshake error from [::1]:47606: remote error: tls: bad certificate
2020/01/08 03:16:30 http: TLS handshake error from [::1]:47610: remote error: tls: bad certificate
2020/01/08 03:16:30 http: TLS handshake error from [::1]:47608: remote error: tls: bad certificate
2020/01/08 03:16:31 http: TLS handshake error from [::1]:47612: remote error: tls: bad certificate
2020/01/08 03:16:31 http: TLS handshake error from [::1]:47614: remote error: tls: bad certificate
```
TLS issues to be resolved elsewhere.

### CODE REVIEW

**Comment by ghost** [comment]
RE: bad cert errors, it's just self-signed...

```bash
# openssl s_client -showcerts -connect localhost:10080 > /tmp/z
depth=0 C = US, ST = California, L = San Francisco, O = Insecure Certificate, OU = For Private Local Communication Only, CN = localhost:10080
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 C = US, ST = California, L = San Francisco, O = Insecure Certificate, OU = For Private Local Communication Only, CN = localhost:10080
verify error:num=21:unable to verify the first certificate
verify return:1
```

**Comment by ghost** [comment]
I'm going to merge this so I can continue with changes to goapi-example, but I will happily fix any issues that are seen after review.

**Comment by dcwangmit01** [comment]
Yes please, merge away.

**Comment by dcwangmit01** [comment]
Changes look great!

**Pull request merged**
